# Generated by Django 4.1.3 on 2022-12-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_uername_contactform_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactForm',
        ),
    ]
